### PR TITLE
Added python3.7.7 compatibility

### PR DESCRIPTION
**Pull request by Filco306**
Hello, 

First of all, thank you for a very nice repository! This was by far the best package I found for a purpose of mine, so I thought I would make it python-compatible, since a lot of my research is made in specifically python. I also added a linter, so code gets cleaned up on commit (assuming pre-commit is installed).

To use the pre-commit linter, ensure you have pre-commit installed through `pip install pre-commit` and then run `pre-commit install` when standing in the repository. 

I added some tests and think this should do it, but I am of course very open to improvements and criticism. 

Best,
Filip

### CODE REVIEW

**Review by hbf — APPROVED** [review]
Thanks a lot, this looks great!

**Comment by Filco306** [comment]
Thank you, and you are welcome! If I were to make a pip-distributable package out of this, would you like it in this repo, or that I build a separate one and refer to this? I think it would be nice to make this even more distributable and even easier for people to access :) Of course if I make it a separate repository, I would refer to this repo to the extent needed!

**Comment by Filco306** [comment]
Will this be merged? @hbf 

thanks :)

**Comment by hbf** [comment]
@Filco306 Sorry for the delay—it's been some time I was working on this project and didn't realize that approval isn't enough for this to get in!

**Pull request merged**
