### PR TITLE
c# port of the java version

### PR DESCRIPTION
**Pull request by devel0**
This PR adds c# support for the miniball library.
Complete of unit tests ( 11 passed, 3 failed, 1 skipped ) like the Java implementation results, with an example like the c++ version and the Getting Started doc.

### CODE REVIEW

**Review by hbf — APPROVED** [review]
Thanks a lot for this contribution, this is great!

Feel free to add yourself to the acknowledgments section if you want: https://github.com/hbf/miniball#authors--acknowledgements

Regarding the unit tests, the three that fail succeed in Java, or what’s the context around these?

**Comment by devel0** [comment]
This happens from java test

```sh
cd java
mvn test
```

results
```
Failed tests:   test_cocircular_points_large_radius_2(com.dreizak.miniball.highdim.MiniballTest)
  test_simplex_10(com.dreizak.miniball.highdim.MiniballTest)
  test_simplex_15(com.dreizak.miniball.highdim.MiniballTest)

Tests run: 15, Failures: 3, Errors: 0, Skipped: 1
```

and corresponding c#

```sh
cd csharp
dotnet test
```

resulting

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.54]     test.MiniballTest.test_cocircular_points_large_radius_2 [FAIL]
[xUnit.net 00:00:00.55]     test.MiniballTest.test_schnarz [SKIP]
[xUnit.net 00:00:00.95]     test.MiniballTest.test_simplex_15 [FAIL]
[xUnit.net 00:00:00.97]     test.MiniballTest.test_simplex_10 [FAIL]
...
Failed!  - Failed:     3, Passed:    11, Skipped:     1, Total:    15, Duration: 703 ms - test.dll (net7.0)
```

details follows:

## test_cocircular_points_large_radius_2

image

## test_simplex_15

image

## test_simplex_10

image

**Comment by devel0** [comment]
From what I can see on my side, for the purpose I used this port, it seems to work nicely, following a sample from an opensource project I'm working on about a multiplatform opengl toolkit, as can see the sphere contains the inner blue tube object:

image

**Comment by hbf** [comment]
Ah, I see, they fail in Java as well. That definitely needs some cleanup/addressing some time but I don’t want you to be blocked by this.

Ok from your side to merge this PR?

**Comment by devel0** [comment]
I have no more commit, for me it can be merged.
Thanks you.

**Pull request merged**
